all:
# Comparing T-bit vectors
	diff KT_0.sdsl KT_1.sdsl
	diff KT_0.sdsl KT_2.sdsl
	diff KT_0.sdsl KT_3.sdsl
	diff KT_0.sdsl KT_4.sdsl
	diff KT_0.sdsl KT_5.sdsl
	diff KT_0.sdsl KT_6.sdsl
	diff KT_0.sdsl KT_7.sdsl

#Comparing L-bit vectors
	diff KL_0.sdsl KL_1.sdsl
	diff KL_0.sdsl KL_2.sdsl
	diff KL_0.sdsl KL_3.sdsl
	diff KL_0.sdsl KL_4.sdsl
	diff KL_0.sdsl KL_5.sdsl
	diff KL_0.sdsl KL_6.sdsl
	diff KL_0.sdsl KL_7.sdsl
